sources_info = {0: {'desc': '"Why I agreed to be vaccinated"',
  'link': 'https://www.qchron.com/opinion/columns/a-moment-in-time-why-i-agreed-to-be-vaccinated/article_dc2caafc-4153-11eb-9a77-2b726956d223.html'},
 1: {'desc': 'A Timeline of Covid-19 Vaccine Development',
  'link': 'https://www.biospace.com/article/a-timeline-of-covid-19-vaccine-development/'},
 2: {'desc': 'About the Varicella Vaccines',
  'link': 'https://www.cdc.gov/vaccines/vpd/varicella/hcp/about-vaccine.html#:~:text=Vaccine%20Effectiveness,-One%20dose&text=1%20dose%20of%20single%2Dantigen,100%25%20effective%20against%20severe%20varicella'},
 3: {'desc': 'Black Americans Distrust New Covid-19 Vaccines',
  'link': 'https://time.com/5925074/black-americans-covid-19-vaccine-distrust/'},
 4: {'desc': "Black Americans' Hesitancy Towards Covid-19 Vaccine",
  'link': 'https://www.cnn.com/2021/02/04/health/vaccine-trust-black-adults-nfid-survey/index.html'},
 5: {'desc': 'Black Vaccine Hesitancy',
  'link': 'https://www.webmd.com/vaccines/covid-19-vaccine/news/20210202/black-vaccine-hesitancy-rooted-in-mistrust-doubts'},
 6: {'desc': 'Black Vaccine Hesitancy Rooted in Mistrust, Doubts',
  'link': 'https://www.webmd.com/vaccines/covid-19-vaccine/news/20210202/black-vaccine-hesitancy-rooted-in-mistrust-doubts'},
 7: {'desc': 'Cancer Rates by Race and Ethnicity',
  'link': 'https://www.cancer.org/content/dam/cancer-org/research/cancer-facts-and-statistics/annual-cancer-facts-and-figures/2020/incidence-and-mortality-rates-race-and-ethnicity-2012-2017.pdf'},
 8: {'desc': 'CDC Covid-19 Guidance',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/communication/guidance.html'},
 9: {'desc': 'CDC Moderna Vaccine Information',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Moderna.html'},
 10: {'desc': 'CDC Pfizer Vaccine Information',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Pfizer-BioNTech.html'},
 11: {'desc': 'COVID-19 Health Equity Interactive Dashboard',
  'link': 'https://covid19.emory.edu/'},
 12: {'desc': 'COVID-19 Racial and Ethnic Health Disparities',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/community/health-equity/racial-ethnic-disparities/disparities-deaths.html'},
 13: {'desc': 'Covid-19 Risk Factors',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html'},
 14: {'desc': 'Current Asthma Demographics',
  'link': 'https://www.lung.org/research/trends-in-lung-disease/asthma-trends-brief/current-demographics'},
 15: {'desc': 'Data and Statistics on Sickle Cell Disease',
  'link': 'https://www.cdc.gov/ncbddd/sicklecell/data.html'},
 16: {'desc': 'Daughter of Tuskegee Received Covid Vaccine',
  'link': 'https://www.centralalabama.va.gov/CENTRALALABAMA/features/Daughter_of_Tuskegee_Receives_COVID_Vaccine.asp'},
 17: {'desc': 'Demographic Characteristics of People Receiving COVID-19 Vaccinations in the United States',
  'link': 'https://covid.cdc.gov/covid-data-tracker/#vaccination-demographic'},
 18: {'desc': 'Health Equity Considerations and Racial and Ethnic Minority Groups',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/community/health-equity/race-ethnicity.html'},
 19: {'desc': 'How mRNA Vaccines Work',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/mrna.html'},
 20: {'desc': 'How to Talk to Your Loved Ones About the Vaccine',
  'link': 'https://incision.substack.com/p/how-to-talk-to-your-loved-ones-about?r=ewzps&utm_campaign=post&utm_medium=email&utm_source=copy'},
 21: {'desc': 'Howard University Vaccine PSA',
  'link': 'https://newsroom.howard.edu/newsroom/article/13676/howard-university-president-issues-vaccine-public-service-announcement-when'},
 22: {'desc': 'Howard University Vaccine PSA Video',
  'link': 'https://www.youtube.com/watch?v=1uotK7FlKOc&feature=youtu.be'},
 23: {'desc': 'In Tuskegee, Painful History Shadows Efforts To Vaccinate African Americans',
  'link': 'https://www.npr.org/2021/02/16/967011614/in-tuskegee-painful-history-shadows-efforts-to-vaccinate-african-americans'},
 24: {'desc': 'Is the Covid-19 Vaccine Safe?',
  'link': 'https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/is-the-covid19-vaccine-safe'},
 25: {'desc': 'Kaiser Family Foundation January poll',
  'link': 'https://beta.documentcloud.org/documents/20478422-embargoed-kff-news-release-for-use-3-am-et-wednesday-jan-27'},
 26: {'desc': 'March of Dimes COVID-19 Pandemic Resources and Support',
  'link': 'https://www.marchofdimes.org/PeriStats/ViewSubtopic.aspx?reg=47&top=16&stop=561&lev=1&slev=4&obj=1'},
 27: {'desc': 'Meet the Black Female Scientist at the Forefront of the Covid-19 Vaccine',
  'link': 'https://www.cbsnews.com/news/covid-19-vaccine-development-kizzmekia-corbett/'},
 28: {'desc': 'National Foundation for Infectious Diseases COVID-19',
  'link': 'https://www.nfid.org/tag/covid-19/'},
 29: {'desc': 'Nurse in NY is First to Get Covid Vaccine',
  'link': 'https://www.businessinsider.com/meet-sandra-lindsay-first-us-person-get-covid-19-vaccine-2020-12'},
 30: {'desc': 'People with Certain Medical Conditions (COVID risks)',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html'},
 31: {'desc': 'Pertussis FAQs',
  'link': 'https://www.cdc.gov/pertussis/about/faqs.html#:~:text=In%20general%2C%20DTaP%20vaccines%20are,effectiveness%20in%20each%20following%20year'},
 32: {'desc': 'Race, Ethnicity, and Kidney Disease',
  'link': 'https://www.kidney.org/atoz/content/minorities-KD#:~:text=Black%20or%20African%20Americans%20are,the%20risk%20for%20kidney%20disease.'},
 33: {'desc': 'Racial and Ethnic Disparities in Adult Obesity in the U.S.',
  'link': 'https://www.cdc.gov/pcd/issues/2019/18_0579.htm#:~:text=Combined%20data%20for%202015%20through,Hispanic%20white%20adults%20(28.6%25).'},
 34: {'desc': 'Racial and Ethnic Disparities in Heart Disease',
  'link': 'https://www.cdc.gov/nchs/hus/spotlight/HeartDiseaseSpotlight_2019_0404.pdf'},
 35: {'desc': 'Racial Disparities with Covid Vaccine',
  'link': 'https://www.aarp.org/health/conditions-treatments/info-2021/racial-disparities-covid-vaccine.html'},
 36: {'desc': 'Racial Diversity Within Covid-19 Vaccine Clinical Trials',
  'link': 'https://www.kff.org/racial-equity-and-health-policy/issue-brief/racial-diversity-within-covid-19-vaccine-clinical-trials-key-questions-and-answers/'},
 37: {'desc': 'Racial Inequities in Covid-19',
  'link': 'https://www.medicalnewstoday.com/articles/racial-inequalities-in-covid-19-the-impact-on-black-communities#Making-sense-of-incomplete-data'},
 38: {'desc': 'Racial Influences on Flu Vaccine Attitudes',
  'link': 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5839483/'},
 39: {'desc': 'Risk for COVID-19 Infection, Hospitalization, and Death By Race/Ethnicity',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/covid-data/investigations-discovery/hospitalization-death-by-race-ethnicity.html'},
 42: {'desc': 'Tackling Vaccine Hesitancy in Churches and on Twitter',
  'link': 'https://www.nature.com/articles/d41586-021-00338-y'},
 43: {'desc': 'The Color of Coronavirus',
  'link': 'https://www.apmresearchlab.org/covid/deaths-by-race'},
 44: {'desc': 'The Covid Tracking Project',
  'link': 'https://covidtracking.com/'},
 45: {'desc': 'The Urgent Need to Build Vaccine Confidence among US Black Adults',
  'link': 'https://www.nfid.org/2021/02/05/nfid-survey-underscores-urgent-need-to-build-vaccine-confidence-among-us-black-adults/'},
 46: {'desc': 'Tuskegee Study ',
  'link': 'https://www.npr.org/2021/02/16/967011614/in-tuskegee-painful-history-shadows-efforts-to-vaccinate-african-americans'}}
