stats_info = {0: {'stat': '10%',
  'info': 'Percentage of Black Americans who had heart disease in 2017',
  'link': 'Link'},
 1: {'stat': '38%',
  'info': 'Percentage of Black Americans who are obese',
  'link': 'Link'},
 2: {'stat': '300% to 400%',
  'info': 'Black women are 3 to 4 times as likely to die during child birth compared to white women',
  'link': 'nan'},
 3: {'stat': '42%',
  'info': 'Percentage by which African Americans are more likely to have asthma compared to white Americans',
  'link': 'nan'},
 4: {'stat': '300%',
  'info': 'Black Americans are 3 times as likely to die from Covid than white Americans',
  'link': 'https://www.medicalnewstoday.com/articles/racial-inequalities-in-covid-19-the-impact-on-black-communities#Making-sense-of-incomplete-data'},
 5: {'stat': '95%', 'info': 'Efficacy of Pfizer vaccine', 'link': 'nan'},
 6: {'stat': '94%', 'info': 'Efficacy of Moderna vaccine', 'link': 'nan'},
 7: {'stat': '21',
  'info': 'Number of days between subsequent doses of the Pfizer vaccine',
  'link': 'nan'},
 8: {'stat': '28',
  'info': 'Number of days between subsequent doses of the Moderna vaccine',
  'link': 'nan'},
 9: {'stat': '10%',
  'info': 'Percentage of clinical trial participants who were African American',
  'link': 'nan'}}
