stats_info = {
 5: {'stat': '95%',
  'info': 'Efficacy of Pfizer vaccine',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Pfizer-BioNTech.html'},
 6: {'stat': '94%',
  'info': 'Efficacy of Moderna vaccine',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Moderna.html'},
 7: {'stat': '21',
  'info': 'Number of days between subsequent doses of the Pfizer vaccine',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Pfizer-BioNTech.html'},
 8: {'stat': '28',
  'info': 'Number of days between subsequent doses of the Moderna vaccine',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/Moderna.html'},
 9: {'stat': '10%',
  'info': 'Percentage of clinical trial participants who were Black',
  'link': 'https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines.html'}}

covid_related ={0: {'stat': '10%',
  'info': 'Percentage of Black Americans who had heart disease in 2017',
  'link': 'https://www.cdc.gov/nchs/hus/spotlight/HeartDiseaseSpotlight_2019_0404.pdf'},
 1: {'stat': '38%',
  'info': 'Percentage of Black Americans who are obese',
  'link': 'https://www.cdc.gov/pcd/issues/2019/18_0579.htm#:~:text=Combined%20data%20for%202015%20through,Hispanic%20white%20adults%20(28.6%25).'},
 2: {'stat': '42%',
  'info': 'Percentage by which Black Americans are more likely to have asthma compared to white Americans',
  'link': 'https://www.lung.org/research/trends-in-lung-disease/asthma-trends-brief/current-demographics'},
  3: {'stat': '300%',
  'info': 'Black Americans are 3 times as likely to die from Covid than white Americans',
  'link': 'https://www.medicalnewstoday.com/articles/racial-inequalities-in-covid-19-the-impact-on-black-communities#Making-sense-of-incomplete-data'}}